project_id = "ulhtyjrohwephsvejtxk"

[functions.admin-manage-users]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.check-scheduled-notifications]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.complete-password-reset]
verify_jwt = false

