import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ClipboardList, Paperclip, AlertTriangle, User, UserRoundPen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';
import type { TaskWorkNote } from '@/types';

interface TaskWorkLogProps {
  notes: (TaskWorkNote & { created_by_name?: string })[];
  isLoading: boolean;
  taskStatus: string;
  onAddNote: (content: string) => void;
  isAdding: boolean;
  canAddNotes?: boolean;
}

const NOTE_TYPE_STYLES: Record<string, { bg: string; icon: React.ReactNode }> = {
  status_change: {
    bg: 'bg-muted/60',
    icon: <ClipboardList className="h-3.5 w-3.5 text-muted-foreground shrink-0" />,
  },
  evidence_upload: {
    bg: 'bg-muted/60',
    icon: <Paperclip className="h-3.5 w-3.5 text-muted-foreground shrink-0" />,
  },
  reopen_reason: {
    bg: 'bg-amber-50 border-amber-200',
    icon: <AlertTriangle className="h-3.5 w-3.5 text-amber-600 shrink-0" />,
  },
  work_note: {
    bg: '',
    icon: <User className="h-3.5 w-3.5 text-muted-foreground shrink-0" />,
  },
};

export function TaskWorkLog({ notes, isLoading, taskStatus, onAddNote, isAdding }: TaskWorkLogProps) {
  const { t } = useTranslation();
  const [noteContent, setNoteContent] = useState('');

  const handleSubmit = () => {
    if (noteContent.trim().length < 10) return;
    onAddNote(noteContent.trim());
    setNoteContent('');
  };

  const showNoteForm = taskStatus === 'in_progress';

  return (
    <div className="space-y-3">
      <h4 className="text-sm font-semibold text-foreground">{t('tasks.workLog.title')}</h4>

      {/* Note form — only when in_progress */}
      {showNoteForm && (
        <div className="space-y-2">
          <Textarea
            value={noteContent}
            onChange={e => setNoteContent(e.target.value)}
            placeholder={t('tasks.workLog.placeholder')}
            rows={3}
            className="text-sm"
          />
          <div className="flex items-center justify-between">
            <span className="text-xs text-muted-foreground">
              {noteContent.trim().length < 10 && noteContent.trim().length > 0
                ? t('tasks.workLog.minLength')
                : ''}
            </span>
            <Button
              size="sm"
              onClick={handleSubmit}
              disabled={noteContent.trim().length < 10 || isAdding}
            >
              {t('tasks.workLog.addNote')}
            </Button>
          </div>
        </div>
      )}

      {/* Notes list */}
      {isLoading ? (
        <div className="space-y-2">
          <Skeleton className="h-12 w-full" />
          <Skeleton className="h-12 w-full" />
        </div>
      ) : notes.length === 0 ? (
        <p className="text-xs text-muted-foreground py-2">{t('tasks.workLog.emptyState')}</p>
      ) : (
        <div className="space-y-1.5 max-h-[400px] overflow-y-auto">
          {notes.map(note => {
            const style = NOTE_TYPE_STYLES[note.note_type] || NOTE_TYPE_STYLES.work_note;
            const isAutoGenerated = note.note_type !== 'work_note';

            return (
              <div
                key={note.id}
                className={`rounded-md border px-3 py-2 text-sm ${style.bg}`}
              >
                <div className="flex items-start gap-2">
                  {style.icon}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs font-medium text-foreground">
                        {note.created_by_name || '—'}
                      </span>
                      <span className="text-[10px] text-muted-foreground tabular-nums shrink-0">
                        {new Date(note.created_at).toLocaleString()}
                      </span>
                    </div>
                    <p className={`text-xs mt-0.5 ${isAutoGenerated ? 'italic text-muted-foreground' : 'text-foreground'}`}>
                      {note.content}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
